export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE'
export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST'

export const SET_CURRENT_TICKET = 'SET_CURRENT_TICKET'
export const SET_CURRENT_QUESTION_POSITION = 'SET_CURRENT_QUESTION_POSITION'
export const INCREASE_WRONG_ANSWERS_COUNTER = 'INCREASE_WRONG_ANSWERS_COUNTER'
export const SET_FINISH_STATUS = 'SET_FINISH_STATUS'
export const RESET_TEST = 'RESET_TEST'